const LANGUAGE_OPTIONS = [
    { name: 'English', code: 'GB' },
    { name: 'Spanish', code: 'ES' },
    { name: 'French', code: 'FR' },
    { name: 'Greek', code: 'GR' },
    { name: 'German', code: 'DE' },
    { name: 'Dutch', code: 'NL' },
    { name: 'Irish', code: 'IE' },
    { name: 'Italian', code: 'IT' },
    { name: 'Romanian', code: 'RO' },
    { name: 'Polish', code: 'PL' },
    { name: 'Croatian', code: 'HR' },
    { name: 'Portuguese', code: 'PT' },
    { name: 'Vietnamese', code: 'VN' },
    { name: 'Malay', code: 'MY' },
    { name: 'Danish', code: 'DK' },
    { name: 'Hungarian', code: 'HU' },
    { name: 'Norwegian', code: 'NO' },
    { name: 'Swedish', code: 'SE' },
    { name: 'Finnish', code: 'FI' },
    { name: 'Arabic', code: 'SA' },
    { name: 'Belarusian', code: 'BY' },
    { name: 'Serbian', code: 'RS' },
    { name: 'Turkish', code: 'TR' },
    { name: 'Russian', code: 'RU' },
    { name: 'Chinese', code: 'CN' },
    { name: 'Korean', code: 'KR' },
    { name: 'Thai', code: 'TH' },
    { name: 'Ukrainian', code: 'UA' },
    { name: 'Bulgarian', code: 'BG' },
    { name: 'Japanese', code: 'JP' },
    { name: 'Slovak', code: 'SK' },
    { name: 'Slovene', code: 'SI' },
    { name: 'Latvian', code: 'LV' },
    { name: 'Estonian', code: 'EE' },
    { name: 'Maltese', code: 'MT' },
    { name: 'Kyrgyz', code: 'KG' },
    { name: 'Georgian', code: 'GE' },
];
export const getLanguageOptions = () => [...LANGUAGE_OPTIONS].sort((a, b) => a.name.localeCompare(b.name));

export default LANGUAGE_OPTIONS;